export const LOCATION_SELECTOR_CONSTANTS = {
  SELECT_CLASSES: "px-4 py-3 bg-gray-50 border border-gray-200 rounded-lg text-sm font-medium text-gray-700 focus:outline-none focus:ring-2 focus:ring-primary-500",
  BULGARIAN_CITIES: [
    "София",
    "Пловдив", 
    "Варна",
    "Бургас",
    "Русе",
    "Стара Загора",
    "Плевен",
    "Сливен",
    "Добрич",
    "Шумен",
    "Перник",
    "Хасково",
    "Ямбол",
    "Пазарджик",
    "Благоевград",
    "Велико Търново",
    "Враца",
    "Габрово",
    "Асеновград",
    "Видин",
    "Казанлък",
    "Кърджали",
    "Кюстендил",
    "Монтана",
    "Димитровград",
    "Търговище",
    "Силистра",
    "Ловеч",
    "Разград",
    "Свиленград",
  ],
} as const;