export const SEARCH_CONSTANTS = {
  SEARCH_PLACEHOLDER:
    "Search attorneys by name, specialization, or law firm...",
  TITLE: "Find Legal Counsel",
  VERIFIED_ONLY_LABEL: "Verified attorneys only",
  LOADING_TEXT: "Finding attorneys...",
  ERROR_TITLE: "Error loading attorneys",
  ERROR_SUBTITLE: "Please try again later",
  ALL_PRACTICE_AREAS: "All Practice Areas",
  ALL_LANGUAGES: "All Languages",

  FILTER_LABELS: {
    PRACTICE_AREAS: "Practice Areas",
    LOCATION: "Location",
    EXPERIENCE: "Experience Level",
    HOURLY_RATE: "Hourly Rate",
    LANGUAGES: "Languages",
    AVAILABILITY: "Availability",
    RATING: "Client Rating",
    CONSULTATION_TYPE: "Consultation Type",
  },

  PLACEHOLDERS: {
    CITY: "Enter city",
    STATE: "Select state",
    MIN_RATE: "Min rate",
    MAX_RATE: "Max rate",
    SELECT_LANGUAGE: "Select languages",
  },

  EXPERIENCE_LEVELS: [
    { value: "all", label: "All Experience Levels" },
    { value: "0-2", label: "New Attorney (0-2 years)" },
    { value: "3-5", label: "Junior (3-5 years)" },
    { value: "6-10", label: "Mid-Level (6-10 years)" },
    { value: "11-20", label: "Senior (11-20 years)" },
    { value: "20+", label: "Expert (20+ years)" },
  ],

  RATE_RANGES: [
    { value: "all", label: "All Price Ranges" },
    { value: "0-150", label: "$0 - $150/hour" },
    { value: "151-300", label: "$151 - $300/hour" },
    { value: "301-500", label: "$301 - $500/hour" },
    { value: "501+", label: "$501+/hour" },
  ],

  AVAILABILITY_OPTIONS: [
    { value: "all", label: "Any Time" },
    { value: "today", label: "Available Today" },
    { value: "this-week", label: "This Week" },
    { value: "next-week", label: "Next Week" },
  ],

  CONSULTATION_TYPES: [
    { value: "all", label: "All Types" },
    { value: "in-person", label: "In-Person Only" },
    { value: "video", label: "Video Call" },
    { value: "phone", label: "Phone Call" },
    { value: "hybrid", label: "Flexible (Any)" },
  ],

  RATING_OPTIONS: [
    { value: "all", label: "All Ratings" },
    { value: "4+", label: "4+ Stars" },
    { value: "4.5+", label: "4.5+ Stars" },
    { value: "5", label: "5 Stars Only" },
  ],

  US_STATES: [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],

  COMMON_LANGUAGES: [
    "English",
    "Spanish",
    "French",
    "German",
    "Italian",
    "Portuguese",
    "Mandarin",
    "Cantonese",
    "Japanese",
    "Korean",
    "Arabic",
    "Russian",
    "Hindi",
    "Dutch",
    "Swedish",
    "Norwegian",
    "Polish",
  ],

  ACTIONS: {
    SEARCH: "Search Attorneys",
    CLEAR_ALL: "Clear All Filters",
    APPLY_FILTERS: "Apply Filters",
    SHOW_FILTERS: "Show Filters",
    HIDE_FILTERS: "Hide Filters",
    BOOK_CONSULTATION: "Book Consultation",
    VIEW_PROFILE: "View Profile",
  },

  AVAILABILITY: {
    EARLIEST_SLOT: "Earliest available:",
    TODAY: "today",
    TOMORROW: "tomorrow",
    THIS_WEEK: "this week",
    NEXT_WEEK: "next week",
  },

  RESULTS: {
    SHOWING: "Showing",
    OF: "of",
    ATTORNEYS: "attorneys",
    NO_RESULTS: "No attorneys found matching your criteria",
    TRY_DIFFERENT: "Try adjusting your filters or search terms",
  },
} as const;
